from ml_api.common.postgre_config import DATABASE_USER, DATABASE_PASSWORD, DATABASE_PORT, DATABASE_HOST

PROJECT_NAME = 'ML Project'
VERSION = '0.0.1'

DEFAULT_DB_NAME = 'ml_project'
DATABASE_URL = f'postgresql://{DATABASE_USER}:{DATABASE_PASSWORD}@{DATABASE_HOST}:{DATABASE_PORT}/{DEFAULT_DB_NAME}'

ALLOW_ORIGINS = ['*']
